services:
  - type: web
    name: threat-intel-backend
    runtime: python
    rootDir: Backend
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ORIGINS
        sync: false
      - key: PYTHON_VERSION
        value: "3.13.0"
